dubbo:
  application:
    name: gpmall-shopping
  registry:
    address: zookeeper://192.168.126.128:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.126.128:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.study.gpmall.shopping

captchaFlag : false
