spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.study.gpmall.shopping.dal.entitys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  port: 9001


